env: "dev"
base_url: "https://pataka.wms.emoha.com/"
browser: "chrome"
api_base_url: "https://xhar538t7ue.emoha.com/"
email: "sumer@gmail.com"
password: "123456"
mobile_number: "349848494"
otp: "31113"
elder_number: "349848494"
country_code: "91"
