env: "dev"
base_url: "https://pataka.wms.emoha.com/"
browser: "chrome"
api_base_url: "http://localhost:3000/api"
email: "sumer@gmail.com"
password: "123456"
phone: "349848494"
otp: "31113"
elder_number: "349848494"