env: "dev"
base_url: "https://pataka.wms.emoha.com/"
browser: "chrome"
api_base_url: "https://xhar538t7ue.emoha.com/"
email: ""
password: ""
mobile_number: ""
otp: ""
elder_number: ""
country_code: "91"
